### ISSUE TITLE
没找到 'dict/dns_servers.txt'

### ISSUE THREAD

**Issue by x7peeps** [lijiejie/subDomainsBrute#17]
运行环境：win10, python2.7,安装了 dnspython 和 gevent
cmd运行：

- [ ] subDomainsBrute.py --full target.com

 报错：

Traceback (most recent call last):
  File "D:\HackProgram\subDomainsBrute-master\subDomainsBrute.py", line 331, in <module>
    d = SubNameBrute(target=args[0], options=options)
  File "D:\HackProgram\subDomainsBrute-master\subDomainsBrute.py", line 36, in __init__
    self._load_dns_servers()
  File "D:\HackProgram\subDomainsBrute-master\subDomainsBrute.py", line 58, in _load_dns_servers
    for server in open('dict/dns_servers.txt').xreadlines():
IOError: [Errno 2] No such file or directory: 'dict/dns_servers.txt'

**Comment by lijiejie** [comment]
先cd D:\HackProgram\subDomainsBrute-master\ ， 再执行试试。 提示是文件不存在，看看dns_servers.txt？

**Comment by x7peeps** [comment]
ok 测了一下
python subDomainsBrute.py --full target.com  -o target.txt  通过
