### ISSUE TITLE
解析的域名不存在时，脚本速度慢

### ISSUE THREAD

**Issue by Withdrawn** [lijiejie/subDomainsBrute#2]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python27\lib\site-packages\dns\resolver.py", line 910, in query
    raise NXDOMAIN
`
当要解析的域名不存在时会出现这个异常,然后脚本就会重试6次, 就出现脚本跑一小会就不动了的情况

**Comment by lijiejie** [comment]
我记得是处理过这个，不会重试的，明天检查看看。  谢谢反馈

⌘李劼杰⌘
