### ISSUE TITLE
windows下用的cmder

### ISSUE THREAD

**Issue by aaeolus** [lijiejie/subDomainsBrute#24]
Traceback (most recent call last):
  File "subDomainsBrute.py", line 10, in <module>
    import gevent
  File "C:\Python27\lib\site-packages\gevent\__init__.py", line 51, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 13, in <module>
    from greenlet import greenlet as RawGreenlet, getcurrent, GreenletExit
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

**Comment by lijiejie** [comment]
hi   这个错误， 看起来是安装的gevent有问题， 可以先删除了重新安装。
注意区分一下 32位 64位   python2版本
尽量通过pip安装
