### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by 687766616e** [lijiejie/subDomainsBrute#34]
```
$ python2 subDomainsBrute.py github.com --full                      SubDomainsBrute v1.2
  https://github.com/lijiejie/subDomainsBrute                                                                                       [+] Validate DNS servers                                          [+] Server 114.114.115.115  < OK >   Found 4                      [+] 4 DNS Servers found                                           Traceback (most recent call last):                                  File "subDomainsBrute.py", line 242, in <module>                    scan_count = multiprocessing.Value('i', 0)                      File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/__init__.py", line 253, in Value
    return Value(typecode_or_type, *args, **kwds)
  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 108, in Value                              lock = RLock()
  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/__init__.py", line 183, in RLock                                  return RLock()                                                  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in __init__                            SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1)
  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__                             sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)                                                            OSError: [Errno 38] Function not implemented
$
```

**Comment by lijiejie** [comment]
git pull可再试试看
