### ISSUE TITLE
EmptyLabel: A DNS label is empty.

### ISSUE THREAD

**Issue by FuckAllWorld** [lijiejie/subDomainsBrute#43]
[-] 0 found, 0 scanned in 4.5 seconds, 0 groups left                                                                                                                                                                                        Traceback (most recent call last):
  File "subDomainsBrute.py", line 128, in scan
    answers = self.resolvers[j].query(cur_domain)
Traceback (most recent call last):
  File "subDomainsBrute.py", line 128, in scan
    answers = self.resolvers[j].query(cur_domain)
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 848, in query
    qname = dns.name.from_text(qname, None)
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 848, in query
    qname = dns.name.from_text(qname, None)
  File "/usr/local/lib/python2.7/dist-packages/dns/name.py", line 925, in from_text
    raise EmptyLabel
  File "/usr/local/lib/python2.7/dist-packages/dns/name.py", line 925, in from_text
    raise EmptyLabel
EmptyLabel: A DNS label is empty.
EmptyLabel: A DNS label is empty.

**Comment by lijiejie** [comment]
能否提供一个测试的域名用于调试

**Comment by luckybool1020** [comment]
> 能否提供一个测试的域名用于调试

www.lend.com.tw
