### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by wilbyang** [lijiejie/subDomainsBrute#46]
Darwin Kernel Version 18.7.0
When I run it, I get 

> Process Process-4:
Traceback (most recent call last):
  File "/Users/boya/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/boya/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./subDomainsBrute.py", line 35, in run_process
    s.run()
  File "/Users/boya/workspace/hacker/subDomainsBrute/lib/scanner_py3.py", line 201, in run
    self.loop.run_until_complete(self.async_run())
  File "/Users/boya/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/Users/boya/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 538, in run_forever
    self._run_once()
  File "/Users/boya/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 1746, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/boya/.pyenv/versions/3.7.6/lib/python3.7/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)
OSError: [Errno 9] Bad file descriptor

**Comment by sevck** [comment]
+1
python3.6
mac

**Comment by KpLi0rn** [comment]
+1 python3.7+ mac 10.15

**Comment by zhangxiang-1222** [comment]
+1
python3.7.5
mac 10.15.5

**Comment by Jasper-Wynn** [comment]
+1
python3.7
mac 10.15

**Comment by lijiejie** [comment]
请大家更新一下代码再试试看。  也请各位看看  ulimit -n 的限制是多少
