### ISSUE TITLE
请问这是什么情况？

### ISSUE THREAD

**Issue by ZZtac** [lijiejie/subDomainsBrute#48]
SubDomainsBrute v1.3  https://github.com/lijiejie/subDomainsBrute
[+] Validate DNS servers
[+] Server 114.114.114.114  < OK >   Found 2                                                                            Traceback (most recent call last):
  File "subDomainsBrute.py", line 47, in <module>
    dns_servers = load_dns_servers()
  File "D:\subDomainsBrute\lib\common_py3.py", line 48, in load_dns_servers
    loop.run_until_complete(async_load_dns_servers(servers_to_test, dns_servers))
  File "D:\python\python3\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "D:\python\python3\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "D:\python\python3\lib\asyncio\base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "D:\python\python3\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "D:\python\python3\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt

**Comment by lijiejie** [comment]
KeyboardInterrupt   可能是不小心按下了Ctrl +C
